export const RESET_STATE = 'RESET_STATE';

export const HELLO_BUTTON_CLICKED = 'HELLO_BUTTON_CLICKED';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'LOGOUT';

export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR';
export const KEYBOARD_WILL_SHOW = 'KEYBOARD_WILL_SHOW';
export const KEYBOARD_WILL_HIDE = 'KEYBOARD_WILL_HIDE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREMENT_CART = 'DECREMENT_CART';

export const MANAGE_ADDRESS = 'MANAGE_ADDRESS';
